### PR TITLE
Make md5 checksum computation asynchronous

### PR DESCRIPTION
**Pull request by iychoi**
- This makes md5 checksum compuatation asynchronous using `delay()`
- Tested locally

### CODE REVIEW

**Comment by tedgin** [comment]
There are a few issues to consider with this implementation.

1. A user could upload a file and immediately rename it, e.g., `iput file; imv file file2`. Since the deferred rule is computing the checksum of the original path, the file won't receive a checksum. It's better to pass the object Id to the deferred rule, and within the deferred rule, resolve the path using the object Id. See `_repl_scheduleMoves` in ipc-repl.re for an example of how to handle this.

2. Replication is already deferred. I'm worried about what happens if a data object is replicated before the original file has had its checksum computed.  What if the file if the replica is corrupted in flight to its storage server? If the original file doesn't have a checksum, that can't be used to verify the replica once its at rest. (iRODS does this automatically if the original has a checksum).  Does this even matter? :shrug: 

3. Some operations compute a checksum on upload, e.g., `iput -k file`. To improve efficiency, we could stop passing the `forceChksum` flag to the microservice. This may be feature creep, since the original checksum logic always performed the checksum. Please consider this just a suggestion. :)

**Comment by iychoi** [comment]
Fixed the first issue. Continue to work on others.

**Review by tedgin — COMMENTED** [review]
The change look logically correct. However, it's better to call a single, named rule from inside  a `defer` block that to call a sequence or logic.  When using `iqstat` to see what's in the rule queue, it shows output like the following.

```console
rods@dev ~? iqstat
id     name
572032 cyverse_housekeeping_determineAllStorageFreeSpace 
572033 cyverse_housekeeping_rmTrash 
572623 
		*dataPath = '';
		foreach (*rec in SELECT COLL_NAME, DATA_NAME WHERE DATA_ID = '*id') {
			*dataPath = *rec.COLL_NAME ++ '/' ++ *rec.DATA_NAME;
		}

		if (*dataPath != '') {
			msiDataObjChksum(*dataPath, *opts, *_);
		}
```

When the deferred logic is wrapped in a named rule, iqstat reports only the named rule call, otherwise it reports the block of rule logic. It's easier to tell what's in the queue when only named rule calls are displayed. 

I suggest renaming `_ipc_chksumRepl` to something like `_ipc_scheduleChksumRepl` and moving the contents of the `defer` block into a rule named something like `_ipc_chksumRepl`.

**Comment by tedgin** [comment]
The changes for making the checksum computation asynchronous look good!  Are you planning on addressing points 2 and 3? If not, I'll merge it.

**Comment by iychoi** [comment]
> The changes for making the checksum computation asynchronous look good! Are you planning on addressing points 2 and 3? If not, I'll merge it.

I plan to take a look for point 2 but not at the moment..

**Comment by tedgin** [comment]
Let's split out points 2 and 3 into separate tasks. Then merge this PR. I'll take care of it.

**Comment by iychoi** [comment]
sounds good. Thanks!

**Pull request merged**
