### PR TITLE
DS-689: Add whitelist file to SFTPGo

### PR DESCRIPTION
**Pull request by iychoi**
This will add a whitelist file to SFTPGo.

The whitelist file is a json file that lists host IPs. The hosts will not be banned in any cases.
The ansible code will not overwrite existing whitelist or blacklist files as we will add new hosts to the list files on the system deployed manually.

### CODE REVIEW

**Review by tedgin — CHANGES_REQUESTED** [review]
Since the whitelist has exactly the same structure, only one file should be stored in version control, and the ansible should be modified so it uses this file to create both the empty whitelist and blacklist files on the SFTP server. The file could be named something like `ip-list.json` or `bypass-list.json`.

**Comment by iychoi** [comment]
Updated the code to not use external files. 
The new code will add hosts to sftpgo.json file directly. The host address can be either IP address or CIDR.

**Review by tedgin — CHANGES_REQUESTED** [review]
The sftp.yml playbook should remove `/etc/sftpgo/blacklist.json`. Also, tests/sftp.yml should verify that blacklist.json is gone instead of verifying it is there. You can remove the test for the existence of `/etc/sftpgo/whitelist.json` since it is not being deployed.

**Comment by iychoi** [comment]
Applied the changes (removing old blacklist.json and not testing).

**Review by tedgin — APPROVED** [review]

**Pull request merged**
